from flask_mongoengine import MongoEngine
from datetime import datetime

db = MongoEngine()

class User(db.Document):
    hunter_id = db.IntField(unique=True)
    username = db.StringField(unique=True)
    facebook_link = db.StringField()
    password_hash = db.StringField()
    role = db.StringField(default='hunter') 
    status = db.StringField(default='active') 
    health = db.IntField(default=100)
    points = db.IntField(default=0)
    zone = db.IntField(default=0)
    inventory = db.ListField(db.StringField(), default=list)
    friends = db.ListField(db.IntField(), default=list)
    friend_requests = db.ListField(db.IntField(), default=list)
    achievements = db.ListField(db.StringField(), default=list)
    avatar = db.StringField(default='👤')
    created_at = db.DateTimeField(default=datetime.utcnow)
    last_active = db.DateTimeField(default=datetime.utcnow)
    last_action_time = db.DateTimeField(default=datetime.utcnow)
    last_health_check = db.DateTimeField(default=datetime.utcnow)
    freeze_reason = db.StringField(default='')
    ip_address = db.StringField()
    chosen_gate = db.IntField(default=0)
    gate_status = db.StringField(default='') 
    gate_test_answer = db.StringField(default='')
    survival_votes = db.IntField(default=0)
    has_voted = db.BooleanField(default=False)
    last_seen_news = db.DateTimeField(default=datetime.utcnow)
    last_seen_puzzles = db.DateTimeField(default=datetime.utcnow)
    last_seen_decs = db.DateTimeField(default=datetime.utcnow)
    last_seen_store = db.DateTimeField(default=datetime.utcnow)
    last_name_change = db.DateTimeField(null=True)
    destroyed_seals = db.IntField(default=0)
    tajis_eye_until = db.DateTimeField(null=True)
    quicksand_lock_until = db.DateTimeField(null=True)
    stats_ghosts_caught = db.IntField(default=0)
    stats_puzzles_solved = db.IntField(default=0)
    stats_items_bought = db.IntField(default=0)

class News(db.Document):
    title = db.StringField()
    content = db.StringField()
    image_data = db.StringField()
    category = db.StringField(default='news')
    author = db.StringField(default='الإدارة')
    created_at = db.DateTimeField(default=datetime.utcnow)
    status = db.StringField(default='approved')
    puzzle_type = db.StringField(default='none') 
    puzzle_answer = db.StringField(default='')
    reward_points = db.IntField(default=0)
    winners_list = db.ListField(db.StringField(), default=list)
    max_winners = db.IntField(default=1)
    current_winners = db.IntField(default=0)
    trap_duration_minutes = db.IntField(default=0)
    trap_penalty_points = db.IntField(default=0)

class StoreItem(db.Document):
    name = db.StringField(required=True)
    description = db.StringField()
    price = db.IntField(required=True)
    image = db.StringField()
    item_type = db.StringField(default='normal') 
    effect_amount = db.IntField(default=0)
    is_luck = db.BooleanField(default=False)
    luck_min = db.IntField(default=0)
    luck_max = db.IntField(default=0)
    is_mirage = db.BooleanField(default=False)
    mirage_message = db.StringField(default='')
    created_at = db.DateTimeField(default=datetime.utcnow)

class GlobalSettings(db.Document):
    setting_name = db.StringField(default='main_config')
    home_title = db.StringField(default='البوابة')
    home_color = db.StringField(default='var(--zone-0-black)')
    banner_url = db.StringField(default='')
    
    global_news_active = db.BooleanField(default=False)
    global_news_text = db.StringField(default='')
    
    maintenance_mode = db.BooleanField(default=False)
    maintenance_until = db.DateTimeField(null=True)
    maintenance_pages = db.ListField(db.StringField(), default=list)
    
    war_mode = db.BooleanField(default=False)
    final_battle_mode = db.BooleanField(default=False)
    bleed_rate_minutes = db.IntField(default=60)
    bleed_amount = db.IntField(default=1)
    safe_time_minutes = db.IntField(default=120)
    dead_count = db.IntField(default=0)
    
    gates_mode_active = db.BooleanField(default=False)
    gates_selection_locked = db.BooleanField(default=False)
    gates_description = db.StringField(default='اختر بوابة...')
    gate_1_name = db.StringField(default='بوابة 1')
    gate_2_name = db.StringField(default='بوابة 2')
    gate_3_name = db.StringField(default='بوابة 3')
    gates_test_message = db.StringField(default='أنت في غرفة الاختبار...')
    
    floor3_mode_active = db.BooleanField(default=False)
    
    nav_home = db.StringField(default='🏠 الرئيسية')
    nav_profile = db.StringField(default='📜 الملف الشخصي')
    nav_friends = db.StringField(default='🤝 الأصدقاء')
    nav_news = db.StringField(default='📜 الأخبار')
    nav_puzzles = db.StringField(default='🧩 الألغاز')
    nav_decs = db.StringField(default='📢 التصريحات')
    nav_store = db.StringField(default='🐪 المتجر')
    nav_grave = db.StringField(default='💀 المقبرة')

class BattleLog(db.Document):
    victim_name = db.StringField()
    weapon_name = db.StringField()
    remaining_hp = db.IntField()
    created_at = db.DateTimeField(default=datetime.utcnow)
